package com.gliesestudio.mc.quickgui.enums;

public enum AwaitingInputType {

    INPUT_NAME,
    INPUT_TITLE,
    INPUT_ROW,
    INPUT_PERMISSION,
    INPUT_ALIAS,

    INPUT_ITEM_NAME,
    INPUT_ADD_ITEM_LORE,
    INPUT_EDIT_ITEM_LORE,

    INPUT_ADD_ITEM_ACTION_LEFT_COMMAND,
    INPUT_ADD_ITEM_ACTION_SHIFT_LEFT_COMMAND,
    INPUT_ADD_ITEM_ACTION_MIDDLE_COMMAND,
    INPUT_ADD_ITEM_ACTION_RIGHT_COMMAND,
    INPUT_ADD_ITEM_ACTION_SHIFT_RIGHT_COMMAND,

    INPUT_EDIT_ITEM_ACTION_LEFT_COMMAND,
    INPUT_EDIT_ITEM_ACTION_SHIFT_LEFT_COMMAND,
    INPUT_EDIT_ITEM_ACTION_MIDDLE_COMMAND,
    INPUT_EDIT_ITEM_ACTION_RIGHT_COMMAND,
    INPUT_EDIT_ITEM_ACTION_SHIFT_RIGHT_COMMAND

}
