name: Maven Package and Release

on:
  release:
    types: [created]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to upload release assets
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Get the JAR filename
        id: get-filename
        run: |
          echo "::set-output name=jar_filename::$(find target -name '*.jar' -print0 | xargs -0 -n1 basename)"

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use secrets.GITHUB_TOKEN, not github.token
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ steps.get-filename.outputs.jar_filename }}
          asset_name: ${{ steps.get-filename.outputs.jar_filename }}
          asset_content_type: application/java-archive